### PR TITLE
Remove extra colon in Account page

### LINKED ISSUE #1911: Double : in the Account page
Screen Shot 2020-05-11 at 10 56 11

### PR DESCRIPTION
**Pull request by blaltarriba**
This diff closes #1911 - in the Account page, remove extra colon in all labels.

### Solution description

Remove extra colon to just leave one.

### UI Changes Screenshot

Before diff:
before

After diff:
after

### CODE REVIEW

**Comment by blaltarriba** [comment]
Done, thank you for your feedback @victorgcramos

**Comment by tiagoalvesdulce** [comment]
Thanks for the PR @blaltarriba! You forgot to change some InfoSection's labels e.g https://github.com/decred/politeiagui/blob/1d09c12716bc26a2cd6cc1922b8934f2d17eb54a/src/containers/User/Detail/Account/AdminAccount.jsx#L229

All the strings passed as the label property to the InfoSection component shouldn't have the `:` at the end.

**Comment by blaltarriba** [comment]
You're right @tiagoalvesdulce I checked again all places where InfoSection is used and I left a few cases. I add a new commit with this changes.

Great feedback @tiagoalvesdulce thank you

**Comment by blaltarriba** [comment]
Sorry @tiagoalvesdulce for missing some, I double checked all places where <InfoSection is used to ensure I don't leave anyone.

**Pull request merged**
