### PR TITLE
Fix bug: version is string lead to fail when request records details

### LINKED ISSUE #2464: Latest version diff not showing up
I could not manage to see the latest version diff from any proposal. As recorded in the video, clicking on the latest version from the dropdown does not trigger anything.

https://user-images.githubusercontent.com/14864439/123919770-921a3180-d985-11eb-8262-4e17bf828d0a.mov

### PR DESCRIPTION
**Pull request by vibros68**
closed #2464

### CODE REVIEW

**Review by lukebp — APPROVED** [review]
tACK

**Review by tiagoalvesdulce — CHANGES_REQUESTED** [review]
Can you use `Number()` instead of `parseInt` to convert the string to a number? The `Number` constructor called as a function should be used to type conversion. For the record, never use `parseInt` without specifying the radix (second argument).

Also, `Solve` isn't a valid keyword to link a PR to an issue. The valid ones are:

* close
* closes
* closed
* fix
* fixes
* fixed
* resolve
* resolves
* resolved

**Comment by vibros68** [comment]
Thank you @tiagoalvesdulce

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM

**Pull request merged**
