### PR TITLE
Politeia e2e tests

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
This PR closes https://github.com/decred/politeiagui/issues/976

### Solution description

I'm adding e2e tests using cypress and react-testing-library/cypress

#### Use Cases

These 2 scripts are responsible to run both the frontend app and the tests, you still have to run the backend as you normally do:

```
"test:e2e:run": "START_SERVER_AND_TEST_INSECURE=1 start-server-and-test start https-get://localhost:3000 cy:run",
"test:e2e:dev": "START_SERVER_AND_TEST_INSECURE=1 start-server-and-test start https-get://localhost:3000 cy:open",
```

The `start-server-and-test` package is important because we have to wait until the server is running to run cypress.

### CODE REVIEW

**Review by victorgcramos — COMMENTED** [review]
👏 👏

**Comment by tiagoalvesdulce** [comment]
It would be nice to be able to make requests programatically with [cy.request()](https://docs.cypress.io/api/commands/request.html#Syntax) but I'm getting a CSRF issue when firing POST requests. See:

Request:
Screen Shot 2020-11-02 at 14 53 42

Response:
Screen Shot 2020-11-02 at 14 45 05

Does anyone know how to work around this?

**Comment by victorgcramos** [comment]
I think we need to enable it on backend. See: https://github.com/decred/politeia/pull/1242, the CMS needs this to bypass the same stuff, I guess.

**Comment by thi4go** [comment]
Hey mate so me and @victorgcramos were able to figure out how to properly set the csrf tokens. I guess now we can have them setup on a `beforeEachRequest` config of cypress or something.

We first waited for the `/api` version call to be completed, then set proper headers with it's response. The gorilla token already gets setup on a cookie with the `set_cookie` header response from the first call. We need to manually set the `X-Csrf-Token` header one. Example on setting the csrf header and then making a login call:

```
 cy.request('https://localhost:3000/api').then((result) =>{ 
    cy
    .request({
      method: 'POST',
      url: 'https://localhost:3000/api/v1/login',
      encoding: 'utf-8',
      body: { email: 'admin@admin.com', password: sha3_256('123123123') },
      headers: {
        'X-Csrf-Token': result.headers['x-csrf-token']
      },
    })
    .then((response) => {
      console.log(response)
    })
  })
```

Think we can write this more clean with es6 async await, but it's just to examplify

**Review by victorgcramos — COMMENTED** [review]
Just one quick feedback... If there's another user with "user2" in its username, like _user231_, the `adminAccount` test will fail, because it expects only 1 user as a result.

**Comment by tiagoalvesdulce** [comment]
hmm, I will fix the tests. We can expect a user or list of users, only a success is enough.

**Review by victorgcramos — APPROVED** [review]
LGTM! Well done, mate! All tests are OK, env working as expected on MacOS. This framework is easy to set up!

Good job on this one!

**Review by amassarwi — APPROVED** [review]
tACK.

Nice work @tiagoalvesdulce!

**Comment by thi4go** [comment]
tACK!

All tests running nicely. Great framework setup @tiagoalvesdulce

**Pull request merged**
