### PR TITLE
Preload user info on invoice submit page

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
I have some questions regarding this PR:

1. Shouldn't we set the contractor rate?
2. We have `githubname` and `matrixname` on the API but there are no fields to set them. Should I add them?
3. Aren't `matrixname` and `contractorcontact` going to be almost always the same?

@alexlyp 

Closes https://github.com/decred/politeiagui/issues/1153

### CODE REVIEW

**Comment by tiagoalvesdulce** [comment]
I didn't _need_ to upgrade them. It's just a simple upgrade and I feel that another PR just for doing that would be unnecessary.

**Comment by amassarwi** [comment]
@tiagoalvesdulce I see, my only concern here is conflicts nothing more, I already did deps change on #1828 and I though we may want to avoid the merge conflicts, it shouldn't be *real* issue I guess.

**Comment by tiagoalvesdulce** [comment]
We can drop the yarn.lock file and do a fresh yarn to generate a new one if the conflicts are an issue.

**Comment by amassarwi** [comment]
@tiagoalvesdulce true, just did it with merging #1825 into #1828

**Pull request merged**
