### PR TITLE
fix: remove vote details call from proposal details page.

### LINKED ISSUE #2460: Remove vote details call from proposal details page
All info we need is already fetched on vote sumaries.

### PR DESCRIPTION
**Pull request by amass01**
Closes #2460.

### CODE REVIEW

**Comment by amass01** [comment]
Testing `Download votes bundle` ...
Waiting to wallet to sync to case some votes.

**Review by lukebp — APPROVED** [review]
tACK

**Review by victorgcramos — APPROVED** [review]
Code looks good! Good job! 🚀

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM

**Pull request merged**
