### PR TITLE
feat: Add flat mode explainer.

### LINKED ISSUE #2458: Add flat mode explainer
**Problem**

The flat mode button looks good, but from a UX perspective new users are unlikely to know what it does.  Flat mode is not a common functionality that people are likely to be familar with.  Comment replies may not be viewable, such as in the example below, so even toggling flat mode on and off is unlikely to provide the user with info about what it does.

image

**Solution**

Add an information icon next to the flat mode button with an explanation of what flat mode does.

image

"Flat mode flattens out the comment hierarchy so that filtering criteria can be applied to both top level comments and comment replies equally.  When flat mode is turned off, filtering criteria is only applied to top level comments."

### PR DESCRIPTION
**Pull request by vibros68**
close #2458 

Flat mode is not a common functionality that people are likely to be 
familar with. Comment replies may not be viewable, such as in the 
example below, so even toggling flat mode on and off is unlikely to 
provide the user with info about what it does.So this pull request 
add a button allow user to hover on it and see the expainer of 
the flat mode button.

flat_mode_explainer

### CODE REVIEW

**Comment by vibros68** [comment]
@lukebp ready for review

**Review by amass01 — CHANGES_REQUESTED** [review]
Thanks for the PR @vibros68:

1. The icon is not vertically centered.
2. As discussed on matrix, the tooltip needs more width.
3. The text need some break lines. Hint: Tooltip component accept
HTML code as content and not only strings.

**Comment by vibros68** [comment]
Thank you @amass01 . I fixed things you say

**Review by lukebp — APPROVED** [review]
tACK

Needs approval from @amass01 and @tiagoalvesdulce.

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM

**Review by amass01 — APPROVED** [review]
LGTM, I would suggest merging this after #2549 as it changes the structure of the files 
touched by this PR.

**Review by victorgcramos — APPROVED** [review]
Good Job! LGTM!

**Comment by lukebp** [comment]
@vibros68 can you fix the merge conflics for this?

**Comment by vibros68** [comment]
Yes I will do

**Comment by lukebp** [comment]
Can you also update your orignal PR message to adhere to the 72 column limit for commit messages?  It allows the person who merges this PR to simply copy and paste the commit message.

https://gist.github.com/lukebp/5a034ba73646903669719b4724a1d945#commit-messages

**Comment by vibros68** [comment]
Yes

**Pull request merged**
