### PR TITLE
fix: quorum text

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
Closes https://github.com/decred/politeiagui/issues/2687

### Dependencies

Depends on https://github.com/decred/pi-ui/pull/412

### UI Changes Screenshot

**Desktop**
Screen Shot 2021-12-20 at 09 21 35

**Mobile**
Screen Shot 2021-12-20 at 09 48 59

### CODE REVIEW

**Review by lukebp — CHANGES_REQUESTED** [review]
image

This is not showing the total eligible votes.  This should say `2/5353 votes`.

**Comment by tiagoalvesdulce** [comment]
Right, my bad.

I'm not feeling good about the UX in this PR tho. Here is a draw of our progress bar with the changes made by this PR:

Screen Shot 2022-01-17 at 17 42 24

While the progress bar max value is the number of votes to reach quorum, the text is displaying votes casted / eligible votes. Pretty confusing.

I suggest we go ahead and implement two bars, one for quorum and one for % of votes. Like @linnutee proposed here: https://github.com/decred/politeiagui/issues/2704. We can get rid of the quorum bar once its reached and show a `quorum reached` text. What do you think @victorgcramos @lukebp @amass01 ?

**Comment by victorgcramos** [comment]
I like linutee's suggestion.

**Comment by victorgcramos** [comment]
See how it looks if we split the view and place the status bars side by side:
Screen Shot 2022-01-17 at 6 50 25 PM

**Comment by lukebp** [comment]
I think you guys are making this way more complicated than it needs to be.  The text from the orignal comment is simple and intuitive.

https://github.com/decred/politeiagui/issues/2687#issuecomment-986981529

A normal person is going to see `100/5000` as the number of votes that have been cast out of the total number of possible votes.  The number of votes until quorum is reached is also displayed.  This lines up with the status bar.

**Review by lukebp — APPROVED** [review]
tACK
image

**Comment by linnutee** [comment]
I commented there in #2704 that adding that two separate bars makes only sense in a proposal specific view. That one has the real-estate to include all the details to make it clear enough. Otherwise much repetition in proposals list view, as that's much more packed already. 

I'd go for a more reductive approach in the prop. list view. Though this is quite dated https://voting.decred.org/ I think solving it with either some icon block as part of the status group, rather than yes/no voting would be optimal. Previous screenshot from Luke is in a sense simple, but adds  too much different type styles w/o alignment. 

Couple quick drafts to test and validate https://www.figma.com/file/igi4pdXlHhTiGyDIF9A2IR/dcr---design-guidelines---id-and-visual-comms?node-id=2%3A7429 :
Screenshot 2022-01-28 at 15 21 02

**Pull request merged**
