### PR TITLE
[CMS] feat: add stats to invoice page

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
Closes https://github.com/decred/politeiagui/issues/1858

### Solution description

Added new params to `admin/invoice` endpoint as well as a new `codestats` endpoint. 

### Dependencies

Depends on https://github.com/decred/politeia/pull/1185 ✅
Depends on https://github.com/decred/politeia/pull/1222 ✅ 
Depends on https://github.com/decred/politeia/pull/1255 ✅ 

### UI Changes Screenshot

Screen Shot 2020-07-23 at 16 05 54

Screen Shot 2020-07-28 at 10 59 35
* Obs: the `pulls` links on this screenshot are a result of old data. I was lazy to drop my db and run `updategithub` again only for this screenshot :)

### CODE REVIEW

**Comment by alexlyp** [comment]
Can we rebase this?

**Comment by alexlyp** [comment]
@tiagoalvesdulce 

I've recently added 2 additions fields to the RepoStats: UpdatedAdditons and UpdatedDeletions.

Should be a pretty simple change to add them to the output as well.  Thanks!

**Comment by alexlyp** [comment]
@tiagoalvesdulce so https://github.com/decred/politeia/pull/1185 has been initially approved by @lukebp, just waiting on final OK from @marcopeereboom .  

In addition to the items above I've also added Commits, CommitAdditions and CommitDeletions. 

Commits is simply just a list of commit URLs so they can be handle just the same way as PRs or Reviews.

CommitAdditions/Deletions can just be added wherever looks the best like the other additions/deletion values.

**Comment by tiagoalvesdulce** [comment]
Great @alexlyp ! I will add the necessary changes to this PR.

**Comment by tiagoalvesdulce** [comment]
Screen Shot 2020-10-19 at 14 49 53

**Comment by xaur** [comment]
Might be worth to truncate invoice and commit hashes to first 7-8 characters to save space.

**Comment by alexlyp** [comment]
@tiagoalvesdulce ok Code stats work has been merged into politeia master.  Could you rebase this to fix the conflicts then i'll give it one more test before we merge it as well

**Review by alexlyp — APPROVED** [review]
tACK

**Pull request merged**
