### PR TITLE
Replace markdown editor

### PR DESCRIPTION
**Pull request by fernandoabolafio**
I've managed to resolve the conflicts to get it merged to Politeia's UI. In the overall it looks pretty good. Maybe won't be necessary to have it forked into Decred's github.

### CODE REVIEW

**Comment by fernandoabolafio** [comment]
Fixes #114

**Comment by tiagoalvesdulce** [comment]
It looks really good but I would say that before we get this merged we should remove `react-markmirror` from the list of dependencies, remove its styles here [/src/style/theme/index.css#L3549](https://github.com/decred/politeiagui/blob/master/src/style/theme/index.css#L3549) and remove this import on [/src/index.js#L6](https://github.com/decred/politeiagui/blob/master/src/index.js#L6).

**Comment by fernandoabolafio** [comment]
Nice catch @tiagoalvesdulce! I've also removed its deps from `yarn.lock` and `package.json`.

**Comment by fernandoabolafio** [comment]
Hold it for while. Found some bugs.

**Comment by fernandoabolafio** [comment]
Bugs fixed. Ready for review.

**Comment by go1dfish** [comment]
Code looks good, I can test out tonight or tomorrow.

I’d like us to switch the preview element up to use this though: https://github.com/decred/politeiagui/blob/master/src/components/snew/Markdown.js

This will ensure the previews match exactly what will be rendered and will make it easier in the future when we want to do image embeds which will likely require custom parsing.

**Comment by fernandoabolafio** [comment]
Replaced! The markdown parser now is the one you've pointed out.

**Comment by fernandoabolafio** [comment]
Fixed

**Comment by fernandoabolafio** [comment]
fixes #88

**Comment by go1dfish** [comment]
Rebase and should be good to merge.

**Pull request merged**
