### PR TITLE
Update visual identity

### LINKED ISSUE #593: Improve visual identity
@saender has made a pretty good job putting together some [logo/symbols assets of politeia](https://github.com/decred/dcrdesign/issues/40). We should adapt pgui to match his design requirements (update the colors, logos, etc). It also includes updating our current loading component. Decrediton is currently using [this gif](https://github.com/decred/decrediton/blob/master/app/style/icons/politeia-loading.gif) and we should use it as well.

### PR DESCRIPTION
**Pull request by camus-code**
closes #593

### CODE REVIEW

**Comment by tiagoalvesdulce** [comment]
Looks good. Like you said on slack, I think the hover effect looks a bit weird. I think we should just change the opacity a little bit. What do you think?

**Comment by camus-code** [comment]
Definitely agree. Changing it now.

**Comment by tiagoalvesdulce** [comment]
OK, reviewing it closely I think we have to adjust some stuff:

1. The loading Icon on the Buttons (like the one on Signup, after the confirmation)
2. The visited state of Buttons
3. The "info" Message (can also be viewed on Signup)

**Comment by tiagoalvesdulce** [comment]
LGTM

**Pull request merged**
