### PR TITLE
Add user option to paste identity & create upload identity modal

### LINKED ISSUE #698: [UI/UX] Allow paste for identity import
The only way to import an identity currently is by importing a file.  Ideally, the dialog would allow you to directly paste the identity as an alternative to requiring a file.

This is desirable because many security conscious users have specialized tools dedicated to storing this type of information encrypted, and, thus, it would be ideal to allow the user to paste it directly instead of first having to create a file to upload.

### PR DESCRIPTION
**Pull request by camus-code**
Closes #698

Also decoupled the PrivateKeyIdentityManager into three separate components (Import, Form, and Download). I think it makes things a little easier to work with.

### CODE REVIEW

**Comment by tiagoalvesdulce** [comment]
https://github.com/decred/politeiagui/pull/880 added some prettifying rules that might be causing some conflicts, `prettier --write "**/*.js"` can be run to apply the prettier rules. Also, a pre-commit script was added and there are [plugins to integrate with most of the text editors](https://prettier.io/docs/en/editors.html).

**Comment by camus-code** [comment]
@tiagoalvesdulce Thanks for the comments! The error message is updated and I think I've resolved the  merge conflicts

**Comment by fernandoabolafio** [comment]
@camus-code  The reason the tests were failing is that you've exported constants from a component file and imported it on the `helpers.js` file, so the component code executed during the tests execution. Please, if you need constants to be used outside of the component scope, define them in the `constants.js` file and import them in the component and in the other files where you need it.

**Comment by tiagoalvesdulce** [comment]
Thanks for fixing the tests, @fernandoabolafio.

I'm still seeing this:
image

Also, the errors are not being cleaned up when the modal is closed. So, if you show an error message, close the modal and then open it again, the messages will still be there.

**Pull request merged**
