### PR TITLE
docs: Add v1.2.0 release notes.

### PR DESCRIPTION
**Pull request by thi4go**

### CODE REVIEW

**Review by victorgcramos — CHANGES_REQUESTED** [review]
Hey @thi4go, can you please make the PR list an unordered list? Looking a little weird on markdown preview:
Screen Shot 2021-09-23 at 1 02 24 PM

**Comment by lukebp** [comment]
You just need to add in markdown line breaks to the end of each line, i.e. add two spaces to the end of each line to indicate a line break.

**Review by lukebp — CHANGES_REQUESTED** [review]
A made a few tweaks.  Please update to the following.

```
politeiagui v1.2.0
====

This release includes the following feature additions, bug fixes and
improvements:

- **Proposal author updates ([#2549](https://github.com/decred/politeiagui/pull/2549)).**
  Proposal authors are now able to give updates on the status of their
  proposal. Updates take the form of new comment threads. Each update creates a
  new comment section in politeiagui that users are able to interact with. The
  proposal author can give as many updates as they would like. Only one update
  thread is allowed to be active at a time. When an author creates a new update
  thread, the previous update thread is locked.

- **Select diff viewer versions ([#2524](https://github.com/decred/politeiagui/pull/2524)).**
  This feature makes it possible to show the diff between any two versions of a
  record. Previously, a user could only use the diff viewer to compare a record
  version with its previous version, e.g. if you wanted to see the diff for
  version 3, it would show the diff between version 3 and version 2. 

- **Embed image button ([#2567](https://github.com/decred/politeiagui/pull/2567)).**
  An embed image button has been added to allow a user to insert an image into
  the proposal markdown file. Previously, the only way to do this was to drag
  and drop the image into the markdown editor at the desired location.

- **Optimistic comment vote updates ([#2520](https://github.com/decred/politeiagui/pull/2520)).**
  Comment votes are now executed optimistically in order to improve the comment
  vote UX. Previously, the vote would not be displayed in the UI until the
  server returned a successful response, creating a delay between when the user
  clicks the upvote/downvote button and when the vote is displayed by the UI of
  the user casting the comment vote. The UI will now display the vote
  immediately on click of the upvote/downvote button, then rewinds the vote if
  the server returns an error.

**Note:** the politeia v1.2.0 release includes additional features like
proposal billing statuses and proposal statuses. These have not been
implemented in politeiagui yet.

## Changelog

This release consists of 35 commits from 6 contributor which total to 112 files
changed, 4,667 additional lines of code, and 1,587 deleted lines of code.

docs: Add v1.1.0 release notes. ([#2526](https://github.com/decred/politeiagui/pull/2526))  
fix: Use short token on record details page ([#2536](https://github.com/decred/politeiagui/pull/2536)) 
feat: Comment vote optimistic updates ([#2520](https://github.com/decred/politeiagui/pull/2520))  
feat: allow user to select diff versions ([#2524](https://github.com/decred/politeiagui/pull/2524))  
e2e: new proposal metadata fields. ([#2512](https://github.com/decred/politeiagui/pull/2512))  
fix: render markdown tables correctly ([#2542](https://github.com/decred/politeiagui/pull/2542))  
fix: Consistent error message for invalid identity ([#2558](https://github.com/decred/politeiagui/pull/2558))  
Add SECURITY.md file ([#2555](https://github.com/decred/politeiagui/pull/2555))  
fix: Make list item format consistent ([#2554](https://github.com/decred/politeiagui/pull/2554))  
fix: Use correct plugin error messages ([#2545](https://github.com/decred/politeiagui/pull/2545))  
fix: Under review tab pagination bug. ([#2552](https://github.com/decred/politeiagui/pull/2552))  
fix: Comments view all navigation bug ([#2559](https://github.com/decred/politeiagui/pull/2559))  
fix(edit proposal): validate initial start date. ([#2560](https://github.com/decred/politeiagui/pull/2560))  
fix: e2e tests. ([#2566](https://github.com/decred/politeiagui/pull/2566))  
feat(new proposal): improve embed image button UX ([#2567](https://github.com/decred/politeiagui/pull/2567))  
fix: use full token in dcrdata charts link. ([#2571](https://github.com/decred/politeiagui/pull/2571))  
fix: Use correct delay for comment votes e2e tests. ([#2579](https://github.com/decred/politeiagui/pull/2579))  
fix: keep comments redux store on logout. ([#2582](https://github.com/decred/politeiagui/pull/2582))  
comments: Add proposal author updates ([#2549](https://github.com/decred/politeiagui/pull/2549))  
fix: Autofocus adjustments on 2FA digits input ([#2553](https://github.com/decred/politeiagui/pull/2553))  
fix: Avoid registration error after unpaid user logout ([#2568](https://github.com/decred/politeiagui/pull/2568))  
fix: Display error message on 2FA modal. ([#2548](https://github.com/decred/politeiagui/pull/2548))  
fix: Under Review pagination issues for big screens. ([#2581](https://github.com/decred/politeiagui/pull/2581))  
fix: Record submission error message position ([#2589](https://github.com/decred/politeiagui/pull/2589))  
feat: Add flat mode explainer. ([#2572](https://github.com/decred/politeiagui/pull/2572))  
fix: Show login modal when user session expires. ([#2541](https://github.com/decred/politeiagui/pull/2541))  
proposal: Data persistence after unvetted logout. ([#2585](https://github.com/decred/politeiagui/pull/2585))  
fix: Remove login modal duplicate props. ([#2594](https://github.com/decred/politeiagui/pull/2594))  
fix: 2FA modal screen flickering. ([#2596](https://github.com/decred/politeiagui/pull/2596))  
fix: Under Review tab infinite loading. ([#2603](https://github.com/decred/politeiagui/pull/2603))  
fix: Comments timestamp download infinite loop. ([#2608](https://github.com/decred/politeiagui/pull/2608))  
test: delete `only` from `Comments downloads` e2e test. ([#2611](https://github.com/decred/politeiagui/pull/2611))  
fix: Type error on comment bundle download ([#2610](https://github.com/decred/politeiagui/pull/2610))  
seo: Add SEO meta tags. ([#2612](https://github.com/decred/politeiagui/pull/2612))  
Revert "seo: Add SEO meta tags." ([#2613](https://github.com/decred/politeiagui/pull/2613))  

## Code Contributors (alphabetical order)

- Amir Massarwa (amass01)
- Đàm Việt Anh (vibros68)
- Degeri (degeri)
- Luke Powell (lukebp)
- Thiago F. Figueiredo (thi4go)
- Victor Guedes (victorgcramos)
```

**Comment by thi4go** [comment]
Done @lukebp 👍

**Review by lukebp — APPROVED** [review]

**Pull request merged**
