### PR TITLE
[redesign] Fix download identity button shifting

### LINKED ISSUE #1419: [redesign] Download identity button shifting
Navigate to your user account page.
Select any other tab besides the Identity tab.
Navigate back to the Identity tab.  The "Download Identity" button starts out in the wrong location then shifts to the right.

### PR DESCRIPTION
**Pull request by amassarwi**
- closes #1419

### CODE REVIEW

**Comment by tiagoalvesdulce** [comment]
Hey @amassarwi, your PR fixes the shifting but would be nice if we could delay the page rendering until the Download Identity button is ready to be rendered. Is it easy to add?

**Comment by amassarwi** [comment]
@tiagoalvesdulce updated

**Comment by amassarwi** [comment]
@tiagoalvesdulce Should be fixed for good now

**Comment by tiagoalvesdulce** [comment]
Good job @amassarwi!

**Pull request merged**
