### PR TITLE
fix: Identity error on billing change modal

### LINKED ISSUE #2656: Incorrect identity error on modal.
The identity error is not being displayed correctly when the error is encountered on the billing status modal.

image

### PR DESCRIPTION
**Pull request by victorgcramos**
Closes #2656.

Fixes Identity error message on Set Billing Status modal.

### UI Changes

**Before:**
before

**After:**
2656-billing-status-identity-error

### CODE REVIEW

**Comment by lukebp** [comment]
This is suppose to use the global identity error that was added in #2623.

**Comment by victorgcramos** [comment]
Hmm okay, I thought the issue was with the message, not the error handling. Got it! Fixing it.

**Review by lukebp — CHANGES_REQUESTED** [review]
This is working correctly if the user does not have an identity loaded in the browser at all, but is not working for when the user has the wrong identity loaded in the browser.  

image

You can reproduce this by logging in using pictl and updating the user's identity with the `pictl userupdatekey` command.  The identity saved to the browser will then be incorrect.

**Review by tiagoalvesdulce — APPROVED** [review]
This code works. But the error is outside the modal and the only way I can leave the Error page is returning to the Home page.
 
Screen Shot 2021-11-18 at 08 34 50

I think this is not the greatest UX. Can we keep the error inside the Modal? I'm not sure if ErrorBoundaries work with React Portal so the ideal solution might not be using them.

**Review by tiagoalvesdulce — CHANGES_REQUESTED** [review]
Approved before by mistake.

**Comment by victorgcramos** [comment]
@tiagoalvesdulce this was defined on #2623. Maybe it's outside the pr scope... Let's open an issue and discuss better solutions for it, what do you think?

**Comment by tiagoalvesdulce** [comment]
oh, forgot about #2623. I'm fine with it but I think we should improve that in the next release. What do you think @lukebp ?

**Comment by lukebp** [comment]
Let's use the global error for now so that we can get the release pushed then open an issue for further improving this UX.

**Review by lukebp — APPROVED** [review]
tACK

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM. @victorgcramos please create the issue so we don't forget to improve it.

**Pull request merged**
