### PR TITLE
[wip][redesign] Hide download of comments on single thread view

### LINKED ISSUE #1424: [redesign] Download Comments Bundle link disappears
In the single comment thread page, the Download Comments Bundle link is being shown for a couple of seconds and then it disappears. I think we shouldn't show it at all.

bug2

### PR DESCRIPTION
**Pull request by fernandoabolafio**
closes #1424

### CODE REVIEW

**Comment by thi4go** [comment]
Hey mate, got a weird behavior on the download link when going back from single comment thread page to proposal page. See below:

Peek 2019-09-23 17-55

**Comment by tiagoalvesdulce** [comment]
It's working fine here.

**Comment by fernandoabolafio** [comment]
I see the issue on my end @thi4go, nice catch! It's a bit tricky because we reset and fetch comments when switching views mode ( single thread or not). I will se if I can come up with a better cache solution for this situation.

**Comment by fernandoabolafio** [comment]
Will be fixed on https://github.com/decred/politeiagui/pull/1448

**Pull request closed without merging**
