### PR TITLE
[WIP] Move text preview next to the editor on proposal submit page

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
Closes https://github.com/decred/politeiagui/issues/155

### CODE REVIEW

**Comment by tiagoalvesdulce** [comment]
Tests failed becasue of https://github.com/decred/politeiagui/issues/147

**Comment by tiagoalvesdulce** [comment]
It can be done @sndurkin. But if the user uses lots of 2 newlines to create paragraphs, the `textarea` will increase its height way faster than the preview and the user might scroll up to see the preview of what he is currently typing and it'd be a bad UX too.

**Comment by sndurkin** [comment]
I agree, but I'm not sure there's much we can do about that particular issue, because it's not a WYSIWYG editor; the preview text will always be larger than the editor text for any headers, which will cause the text to get out of sync as well. Maybe it's better to eliminate the scrollbar for the entire page and just have independent scrollbars for the editor and preview?

**Comment by tiagoalvesdulce** [comment]
I don't think all these scrolls look good. Also, our screen doesn't fit on only one view height so we need the page scrollbar. I tested both approaches and the `textarea` resize works better in my opinion.

**Pull request merged**
