### PR TITLE
[cms] Allow invoice submission for sub contractors

### LINKED ISSUE #1471: [cms] Update invoice submission for SubContractors
https://github.com/decred/politeia/pull/1023

This recent politeia PR adds the ability to denote a given line item as a billed subcontractor hours.

It also adds a new request so users may return a list of subcontractors that are using them as a supervisor. This will allow us to populate a dropdown (when in the new type 4) with their list and they can simple select their subcontractor for that line item.

### PR DESCRIPTION
**Pull request by victorgcramos**
Closes #1471.

One quick observation: since there is no `contractor rate` field, the subtotal will not take the `Labor (hours)` line item into consideration when calculating the `Subtotal`. Therefore, the only way to modify the `Subtotal` value is to put the subcontractor's payout amount into the `Expense` field.

### CODE REVIEW

**Comment by fernandoabolafio** [comment]
@victorgcramos it's working nicely. Two things I noticed:

1. This is minor but it took me a while to figure out: trim the user ids in the Manage User tab when adding supervisors to a user.

2. Since we don't have the contractor rate info yet, I think we should block the "hours" field and use the expenses only. At least for now. What do you think @alexlyp?
Also, when I set some value in the hours' field, it changes the subtotal to 0, even if I had an expense placed on.

**Comment by alexlyp** [comment]
Hrm yah I suppose that would be a reasonable fix for the time being.  Let me get this contractor rate added to the line item so it can be updated properly.  Let's put a quick hold on this PR in that case.

**Comment by alexlyp** [comment]
OK i've completed work on the required politeia PR.  https://github.com/decred/politeia/pull/1044

You'll need to update your local DB by doing: "ALTER TABLE line_items ADD contractor_rate int;"

**Comment by victorgcramos** [comment]
Just found out that this also Closes #1301

**Comment by alexlyp** [comment]
This needs a rebase

**Comment by alexlyp** [comment]
Hrm getting an error when running it: 

./src/components/DCC/Details/Details.jsx
Module not found: Can't resolve 'snew-classic-ui' in '/home/user/git/src/github.com/decred/politeiagui/src/components/DCC/Details'

**Pull request merged**
