### PR TITLE
Centers box and creates white wrapper & visual division

### LINKED ISSUE #437: check your inbox: center text, larger font
text is all left justified and reads poorly on a wider screen, suggest moving the content div to a more centered location. font size is ok, maybe a little small.

### PR DESCRIPTION
**Pull request by rrecuero**
Closes #437 

- Increases text size
- Creates text wrapper with visual separation and centers it

Before
screen shot 2018-07-14 at 1 49 02 pm

After
screen shot 2018-07-14 at 1 48 42 pm

### CODE REVIEW

**Comment by rrecuero** [comment]
@sndurkin

**Comment by dajohi** [comment]
@rrecuero please rebase against master.

**Comment by rrecuero** [comment]
merged with master @dajohi

**Comment by rrecuero** [comment]
Done @sndurkin  :)

**Pull request merged**
