### PR TITLE
feat: allow user to see raw markdown

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
Closes https://github.com/decred/politeiagui/issues/2415
Depends on https://github.com/decred/pi-ui/pull/339

https://user-images.githubusercontent.com/13955303/121043004-9e4a0f00-c78a-11eb-8925-43f1b5b49c24.mp4

### CODE REVIEW

**Comment by lukebp** [comment]
Might it be better to create an icon for it and add it to this list?  Seems like the appropriate place for it and would be cleaner.

image

**Review by lukebp — APPROVED** [review]
ACK

When you merge this, can you include an explanation in the commit message for why we decided to render the markdown on a different page vs a toggle that renders it in place?  The thought process behind these design decisions is important to document in case we need to re-visit this feature in the future.  Might not be a bad idea to include this in the codebase too.

**Review by amassarwi — APPROVED** [review]
code LGTM

**Comment by xaur** [comment]
Adding to the commit message (62879da), "opening raw Markdown in a new tab" translates to "raw Markdown has its own unique URL", which is a very desirable property for any _resource_ or piece of content. Now it is easy to script (`curl https://proposals.decred.org/record/2895755/raw`), which also means the content can be accessed without javascript (and even without browser!), and software like browsers or download managers will have a working link to resume/restart the download.

**Pull request merged**
