### PR TITLE
fix: Use short token on record details page.

### LINKED ISSUE #2535: Record details page never stops loading for full tokens on URL
Here's a live preview of it: https://test-proposals.decred.org/record/a6a5084634555d15

Screen Shot 2021-08-11 at 7 31 30 PM

All requests succeeded , but the proposal is still loading, and seems to be locked in this state.

### PR DESCRIPTION
**Pull request by victorgcramos**
Closes #2535

### CODE REVIEW

**Comment by lukebp** [comment]
@victorgcramos what PR introduced this bug and can we add tests to prevent this from happening in the future?

**Comment by victorgcramos** [comment]
https://github.com/decred/politeiagui/pull/2454 introduced it.

Added e2e tests for proposal details page.

**Review by lukebp — APPROVED** [review]
Interesting.  Thanks for adding the tests.

ACK

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM

**Pull request merged**
