### PR TITLE
[voting] display voting stats #579

### PR DESCRIPTION
**Pull request by victorgcramos**

### CODE REVIEW

**Comment by victorgcramos** [comment]
#579

**Comment by tiagoalvesdulce** [comment]
Thanks, @victorgcramos. Please make sure to edit the PR description to close the issue automatically when it's merged. See [closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by victorgcramos** [comment]
@fernandoabolafio the TimeAgo component is not the best solution because it shows the "Time Ago" message... I think the best alternative for date formatting is [react-moment](https://www.npmjs.com/package/react-moment#from-now-during)

**Comment by tiagoalvesdulce** [comment]
Hey @victorgcramos, just adding to @fernandoabolafio's review. Can you consider using [date-fns's distanceInMilliseconds](https://date-fns.org/v1.29.0/docs/differenceInMilliseconds) and then format the difference to date (days, minutes, seconds)? Because moment + react-moment are 17.7kb gizipped, which is a lot bundle size for just displaying some date difference. date-fns's distanceInMilliseconds adds just 3.2kb to the bundle size instead.

**Comment by victorgcramos** [comment]
@tiagoalvesdulce @fernandoabolafio oh, good points!! Sure, I'll do that!

**Pull request merged**
