### PR TITLE
[redesign] Highlight new comments since last visit

### LINKED ISSUE #1348: [redesign] Highlight of new comments since last visit
Implement the highlight of new comments since the last visit.

### PR DESCRIPTION
**Pull request by fernandoabolafio**
closes #1348 

@MariaPleshkova I needed to add some padding to the comments frames so the gray background looks good on it. With that, the top-level comments are no longer aligned to the title, I didn't think of any other way of doing that. It looks good to me though. Let me know what you think:
Screen Shot 2019-08-29 at 18 10 24

### CODE REVIEW

**Comment by fernandoabolafio** [comment]
@MariaPleshkova I adjusted the comments to allow it to grow a bit wider than the container:
Screen Shot 2019-08-30 at 13 28 39

For mobile, I am hiding the  "new" and keeping only the background. I also found better to have the comments container to occupy the full width: 
Screen Shot 2019-08-30 at 13 28 19

**Comment by MariaPleshkova** [comment]
move it closer to the edge
image

**Comment by MariaPleshkova** [comment]
@thi4go hm, yes, it makes sense.
@fernandoabolafio I think we can try to add smth like this:
image

**Comment by fernandoabolafio** [comment]
@thi4go @MariaPleshkova updated! The results is shown in this [video](https://gofile.io/?c=OBMZmp).

**Comment by thi4go** [comment]
Looking great! @fernandoabolafio LGTM

**Pull request merged**
