### PR TITLE
Authenticate /user/resend route

### LINKED ISSUE #1197: [cms] /user/resend error
When my verification token expired, I pressed the resend button and got this:

> The server encountered an unexpected error, please contact Politeia administrators and include the following error code: <unix timestamp>

It could be a more user friendly message explaining what went wrong.

### PR DESCRIPTION
**Pull request by camus-code**
Closes #1197 

This commit updates the /user/resend route to be protected behind admin authentication

### CODE REVIEW

**Comment by alexlyp** [comment]
That isn't a viable route on CMS.  The only way an invitation email can be resent is for an admin to complete the invitation form again.

**Comment by alexlyp** [comment]
The linked issue is not valid anymore and can be closed I believe.  There no longer is a link shown on that page in CMS.  Thought not sure whether the bit about "flashing" is still there.

**Comment by camus-code** [comment]
Ah okay I misunderstood the /user/resend route. I suppose I can go ahead and remove the related routes for CMS entirely for this PR. As for the "flashing" bit, that was another bug fixed by #1234.

So yes the linked issue can be closed

**Comment by alexlyp** [comment]
Yah please go ahead and just remove this route entirely for CMS

**Comment by camus-code** [comment]
Sorry some things came up yesterday. Just pushed a new commit to remove these routes @fernandoabolafio @alexlyp

**Pull request merged**
