### PR TITLE
fix: Under Review pagination issues for big screens.

### LINKED ISSUE #2580: Under Review tab pagination not working for 5 authorized proposals.
The current "Under Review" tab is not rendering the `unauthorized` proposals when there are 5 `authorized` on list for long height screens.

under-review-authorized

Here's the `/inventory` response:

```json
{
    "vetted": {
        "approved": [
            "667e4c08f2ae7046"
        ],
        "authorized": [
            "f61053aefdb2cf5e",
            "fbc063ef51c0f715",
            "5864bfa2909a4851",
            "df5655878846ff10",
            "8e7f9d7e4f408613"
        ],
        "ineligible": [
            "faf00e553d58256e",
            "303644e68ed9c533",
            "1f47fdabda77ab3e",
            "d22a532f845a6026",
            "5f0f9f72259b702d",
            "b455beef30f45d2c",
            "28dd7465d2d00526",
            "44d1df1319ba6611",
            "5ee747e601df1e68"
        ],
        "unauthorized": [
            "238c041afdef512a",
            "5a7dafa92b303913",
            "45707323e959952c",
            "76468a996ab86274",
            "3a0a76ac44cc140a",
            "6ee627dc9afe9217",
            "94432aa6972ba625",
            "0281472674643862",
            "e917eee7d134f419",
            "e1c892aa37dd5f36",
            "784f8376f1faf33e",
            "793c1e9a1a3b1b1c",
            "a80c5d7072dff868",
            "ddbc3f20b7108f39",
            "22fd4f713e207204",
            "ac4e67b2101c2a1f",
            "dfd0fc00e441d650",
            "50c14c5caccd0327",
            "fdfea0e42ab0ac2a",
            "99996d60421fbf4e"
        ]
    },
    "bestblock": 766537
}
```

### PR DESCRIPTION
**Pull request by victorgcramos**
Closes #2580

This diff fixes some pagination issues for inventories with the same tokens amount as the proposal page size, rendering for big screens. Also, adds e2e tests to cover these cases.

### CODE REVIEW

**Comment by vibros68** [comment]
Hi @victorgcramos . Thank you for your pull request. Your code is looing good for me. Also the addition e2e test case is great. I get the failling at `Big screens` test cases. Can you check again?
Screenshot from 2021-09-15 13-42-44

**Comment by victorgcramos** [comment]
Waiting for #2549.

**Comment by victorgcramos** [comment]
@vibros68 good catch, mate. Fixed! It's ready for another review.

**Comment by vibros68** [comment]
LGTM @victorgcramos

**Review by lukebp — APPROVED** [review]
ACK

Needs final approval from @tiagoalvesdulce.

**Review by tiagoalvesdulce — APPROVED** [review]
LGTM

**Pull request merged**
