### PR TITLE
[cms] fix: reword invoice title

### PR DESCRIPTION
**Pull request by tiagoalvesdulce**
Closes https://github.com/decred/politeiagui/issues/2234

### CODE REVIEW

**Review by victorgcramos — APPROVED** [review]
LGTM! Thanks for the PR! I think we can remove this "invoice" and leave just the `user - date` format on listing. IMO, we should just use the "invoice" word on details. Just to avoid the redundancy on invoice listing. But it's my opinion.

**Comment by xaur** [comment]
We could live without "invoice" too :)

A combination of username and date makes it obvious that it is an invoice. It may change when we get another entity with similar short text representation, but then we could just add "invoice" back.

**Review by victorgcramos — APPROVED** [review]
tACK!

**Review by amassarwi — APPROVED** [review]
lgtm

**Pull request merged**
