### PR TITLE
[Redesign] Proposals: public list, details and form

### PR DESCRIPTION
**Pull request by fernandoabolafio**
This PR implements parts of the Milestone 2 for the redesign.
Here is what is covered so far:
- Public proposals list
- Proposals details
- Proposal form (partially b/c it needs a few things from the redesign listed on https://github.com/decred/dcrdesign/issues/159 and other adjustments on my side). 
- User account -> proposals tab

There are a couple of UI tweaks that should be addressed while this PR is still in progress or in subsequent PRs.
Other proposal features listed for milestone 2 will be included in the next Pull request.

This PR is rebased on top of #1295.

Also, depends on:
- https://github.com/tiagoalvesdulce/pi-ui/pull/63
- https://github.com/tiagoalvesdulce/pi-ui/pull/61

### CODE REVIEW

**Comment by fernandoabolafio** [comment]
@MariaPleshkova @linnutee this PR is ready for a review from you now. A few things I would like to note:

1. Public Proposals tabs:
 As of now, I kept the horizontal flow for tabs as they are looking quite decent for mobile screens. I created an issue (https://github.com/tiagoalvesdulce/pi-ui/issues/77) for an alternative tab view for mobile, which can be used to replace the current approach in the near future.
Jul-08-2019 18-39-06

2. Votes counting display on top of percentages of "yes" and "no" instead of on the side.
The design spec did not take into consideration big numbers of votes, which makes the content of choices percentage (yes/no) and votes counting too squeezed side-by-side. The solution was to pull the counting up whenever that happens:
Screen Shot 2019-07-08 at 18 41 05

3. Proposal token display:
I wasn't able to export the assets placed on the side of the proposal token from the current preview URL. I need the adobe file to export it properly. I will be adding that in my next PR. In that matter, we are also waiting for a properly spec of how tokens/keys should be displayed.

**Comment by lukebp** [comment]
I had a question for @MariaPleshkova:

1. The first thing that gets loaded in the list view are the proposal count numbers for each tab.  There's no visual cue that anything is being loaded while these numbers are being fetched.  The loading visual doesn't start until after the tab counts have been populated and the the proposals are being loaded.  Should there be some type of loading visual during this first part?

Everything else was looking pretty good.  I was going to bring up the mobile proposal list view, but @fernandoabolafio already mentioned that.

**Comment by lukebp** [comment]
Actually, noticed one other thing.  There's no loading visual while the user details proposals are being loaded.  Is this intentional @fernandoabolafio?

**Comment by fernandoabolafio** [comment]
@lukebp yes, this is intentional. I am not putting that much effort on loading indicators for now because we're waiting on the design specs for it (see here https://github.com/decred/dcrdesign/issues/159).

**Comment by MariaPleshkova** [comment]
@fernandoabolafio 
1.commented in the Pull request (already created an alternative view. I'll send it to this (tiagoalvesdulce/pi-ui#77) issue soon)
2. commented in the Pull request (we changed it on mobile views. Now there's only "# votes left". I think it will help)

4.I think it's ok. The only thing is there will be one more field ("choose category") above all of the rest fields. (you'll see it in the tweaked version) 
Small preview:
image

**Comment by fernandoabolafio** [comment]
@MariaPleshkova thanks for your review. I will start addressing your comments. 

I will answer two of your comments in a single shot as they are co-related:
>4. I think it's ok. The only thing is there will be one more field ("choose category") above all of the rest fields. (you'll see it in the tweaked version)
Small preview:
> 8. as far as I understand we leave only 1 line of categories(in discussion, voting,etc.) for now?
We don't have the 'categories'

The categories feature (selecting development, marketing, etc) isn't implemented yet. It is very good to have it designed already. However, since we have so many things on our plate right now, I will leave those bits to be implemented once we have this feature built in the backend.

**Comment by MariaPleshkova** [comment]
@lukebp Do you mean this pause before something appears on the screen? (white screen with nothing on it).
Or the small pause after that: 
image
?

**Comment by fernandoabolafio** [comment]
@MariaPleshkova  We're targeting a testnet update using the redesigned website very soon, so I am prioritizing macro areas over a few improvements. That said,  I've addressed all of your comments. except for the following:

7- Search proposals icon: I will hold this for a bit as the proposals searching by tokens is not a crucial feature so I can invest time on key parts of the redesign which haven't been touched yet such as comments.

14- Dropdown tabs: We will be creating the alternative view for tabs in the following days because of the same reason stated on 7. This issue is tracked here: https://github.com/tiagoalvesdulce/pi-ui/issues/77.

**Comment by lukebp** [comment]
@MariaPleshkova I was referring the screen that you captured in that screenshot.  Depending on network latency and where you're located, this screen could be showing for anywhere from half a second to a few seconds.

**Comment by MariaPleshkova** [comment]
@lukebp I think it can be solved by adding this effect of blinking gray cards once the page starts showing any content on it. I mean we can just add a few (eg 3 or 4) of these gray rectangles even before the system counts the numper of proposals. What do you think @fernandoabolafio ?

**Comment by fernandoabolafio** [comment]
@MariaPleshkova move this discussion to here please: https://github.com/decred/politeiagui/issues/1308

**Comment by MariaPleshkova** [comment]
While reviewing attaching files to proposal implementation, noticed a few things regarding the form itself:

1. Do we really need this notification? I mean, is it necessary to restrict people to 8 characters?
image

2. When I switch to preview, the buttons Submit and Save as draft moves a little bit up

3. It's weird that the style of text Nothing to preview is the same as Write your proposal, because the first one is a template, while the second is not. So we have to change the second one's style. I'd go with #596D81 color and remove text field's frame (replace it with just a line #E6EAED)
image

4. All of these don't work (idk, maybe it is just not implemented yet, so just in case)
image

**Pull request merged**
