### PR TITLE
Feature: mark new comments as read manually

### PR DESCRIPTION
**Pull request by victorgcramos**
This commit allows users to manually mark comments as read, as we discussed on #1021

- adds "mark as read" option to each comment
    - read comments can be marked as unread
- style changes for supporting the new design for new comments
- adds www calls for persisting read comments data for each user
- clicking on unread comment's body sets it as read
- like action toggles read comment state for comment

### CODE REVIEW

**Comment by victorgcramos** [comment]
#### [TODO] Set comments as read when:
- [ ] Upvoting/downvoting
- [ ] Reply
- [ ] Click on comment's box (?)
#### Done
- [x] Send new comment

**Comment by xaur** [comment]
> Click on comment's box

Yes please, it's very fast to target because the box is big enough, and is perhaps touch friendly. This is how it works on Reddit btw.

> allows multiple comment selection to mark multiple comments as read or unread

This implies some selection and unselection UX. How? Checkboxes?

**Comment by victorgcramos** [comment]
Yes! Checkboxes!

**Comment by xaur** [comment]
Checkboxes on all comments would add a lot of visual noise. Honestly, I'm not sure right now that the feature to select multiple comments is necessary. This makes the process of marking them as read to complex: first click a dozen checkboxes and then press some "Mark as read" button. It would be much simpler to just click comment areas of the same comments.

**Comment by victorgcramos** [comment]
I have the screen preview for that. Let me know what you think!
Captura de Tela 2019-04-06 às 15 21 30

**Comment by xaur** [comment]
I still think checkboxes is an overkill.

Behavior like Reddit's unread message box would be ideal - the whole comment bounding box has a bit greyish or bluish background, and when you click anywhere on it it toggles the state between read/unread. I would just read through the comments and spend 1 click on each, instead 1 click on each checkbox and then an extra click on "mark as read".

Feel free to ask more people.

**Comment by fernandoabolafio** [comment]
@victorgcramos what is the status of the backend work for this issue? Can you link it here?

**Comment by fernandoabolafio** [comment]
This feature has been rejected as per @lukebp [comments](https://github.com/decred/politeiagui/issues/1021#issuecomment-486679698) so this PR is not applicable anymore. It is a good practice to always validate new features with other devs in the matrix channel. It saves you some hours of coding :)

**Comment by xaur** [comment]
@fernandoabolafio to my memory a feedback on the issue and PR was requested multiple time in chat with zero reply. Perhaps pursuing it without any feedback was not a good idea, but devs not replying to multiple requests like this is a problem too.

**Comment by fernandoabolafio** [comment]
I agree @xaur. I'm not here to blame anyone. Let's just try to improve the communication between the two sides next time so we make sure that every feature enters the coding stage with enough validation from the most experienced devs.

**Pull request closed without merging**
