### PR TITLE
improve markdown 

### LINKED ISSUE #137: Inconsistency between the markdown editor and the preview
On the proposal submit page, if you select a multiline block of code in the markdown editor and then click the code button, it will wrap the highlighted text with triple backticks, but they aren't displayed correctly in the markdown preview component:

image

The markdown preview component does correctly display code indented by 4 spaces, though.

### PR DESCRIPTION
**Pull request by fernandoabolafio**
Now I've switched to react-markdown as we discussed on #140. 
This markdown cover lots of security potencial issues but we need still to figure out which approach to take for embedded images/links. 
@go1dfish looks like this can make our life easier handling links: 
https://github.com/rexxars/react-markdown/issues/124
Are we going to block any sort of external links?

 fixes #137

### CODE REVIEW

**Comment by fernandoabolafio** [comment]
One thing that might work is to trigger some alert like this when a user clicks some link:
```
 ______________________________
|          Alert               |
|      Follow this link        |
|      at your own risk        |
|      -> link                 |
|______________________________|
```

**Comment by dajohi** [comment]
This fails to build on node 8, which is required.

**Comment by go1dfish** [comment]
I don't think we need to block all external links, but we should mark them as nofollow.

All external embedded images need to be blocked or just rendered as a text link to the image.

We have no solution for handling attached image embeds yet, but I expect what we will do is use a filename reference in the image markdown and render it with an img tag using the base64 file data.  

I wouldn't worry about attached image embeds yet as the current renderer doesn't handle these either.

**Comment by fernandoabolafio** [comment]
`react-markdown`actually can render embedded images, see:
screen shot 2017-12-12 at 2 33 55 pm
But they also provide an api method for transforming images, from their docs:

- transformImageUri - function|null Function that gets called for each encountered image with a single argument - uri. The returned value is used in place of the original.

**Pull request merged**
